function C = C_vector_func(in1,in2,in3)
%C_vector_func
%    C = C_vector_func(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Jul-2025 12:22:28

Ibx = in3(3,:);
Iby = in3(4,:);
Ibz = in3(5,:);
l = in3(9,:);
mw = in3(2,:);
phi = in1(4,:);
phid = in2(4,:);
psid = in2(6,:);
theta = in1(5,:);
thetad = in2(5,:);
w = in3(10,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = l.^2;
t7 = phi.*2.0;
t8 = psid.^2;
t9 = theta.*2.0;
t10 = thetad.^2;
t11 = w.^2;
t12 = t2.^2;
t13 = t3.^2;
t14 = sin(t7);
t15 = sin(t9);
mt1 = [0.0;0.0;0.0;(Iby.*t10.*t14)./2.0-(Ibz.*t10.*t14)./2.0-Ibx.*psid.*t3.*thetad+Iby.*psid.*t3.*thetad-Ibz.*psid.*t3.*thetad-mw.*t10.*t11.*t14.*3.0-Iby.*psid.*t3.*t12.*thetad.*2.0+Ibz.*psid.*t3.*t12.*thetad.*2.0-Iby.*t2.*t4.*t8.*t13+Ibz.*t2.*t4.*t8.*t13-mw.*psid.*t3.*t11.*thetad.*1.2e+1+mw.*psid.*t3.*t11.*t12.*thetad.*1.2e+1+mw.*t2.*t4.*t8.*t11.*t13.*6.0];
mt2 = [Ibx.*t8.*t15.*(-1.0./2.0)+(Iby.*t8.*t15)./2.0-Iby.*phid.*t14.*thetad+Ibz.*phid.*t14.*thetad+mw.*t6.*t8.*t15.*2.0-mw.*t8.*t11.*t15.*3.0+Ibx.*phid.*psid.*t3-Iby.*phid.*psid.*t3+Ibz.*phid.*psid.*t3+Iby.*phid.*psid.*t3.*t12.*2.0-Ibz.*phid.*psid.*t3.*t12.*2.0-Iby.*t3.*t5.*t8.*t12+Ibz.*t3.*t5.*t8.*t12+mw.*phid.*psid.*t3.*t11.*1.2e+1+mw.*phid.*t11.*t14.*thetad.*6.0-mw.*phid.*psid.*t3.*t11.*t12.*1.2e+1+mw.*t3.*t5.*t8.*t11.*t12.*6.0];
mt3 = [-Ibx.*phid.*t3.*thetad-Iby.*phid.*t3.*thetad+Ibz.*phid.*t3.*thetad+Ibx.*psid.*t15.*thetad-Iby.*psid.*t15.*thetad+Iby.*phid.*t3.*t12.*thetad.*2.0-Ibz.*phid.*t3.*t12.*thetad.*2.0-Iby.*t2.*t4.*t5.*t10+Ibz.*t2.*t4.*t5.*t10-mw.*psid.*t6.*t15.*thetad.*4.0+mw.*psid.*t11.*t15.*thetad.*6.0-mw.*phid.*t3.*t11.*t12.*thetad.*1.2e+1+mw.*t2.*t4.*t5.*t10.*t11.*6.0+Iby.*phid.*psid.*t2.*t4.*t13.*2.0-Ibz.*phid.*psid.*t2.*t4.*t13.*2.0+Iby.*psid.*t3.*t5.*t12.*thetad.*2.0-Ibz.*psid.*t3.*t5.*t12.*thetad.*2.0-mw.*phid.*psid.*t2.*t4.*t11.*t13.*1.2e+1-mw.*psid.*t3.*t5.*t11.*t12.*thetad.*1.2e+1;0.0;0.0;0.0;0.0;0.0;0.0];
C = [mt1;mt2;mt3];
end
