function G = G_vector_func(in1,in2)
%G_vector_func
%    G = G_vector_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Jul-2025 09:46:04

g = in2(7,:);
mb = in2(1,:);
mw = in2(2,:);
G = [0.0;0.0;g.*mb+g.*mw.*6.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
end
